### ISSUE TITLE
Please set timezone

### ISSUE THREAD

**Issue by ptr727** [ehough/docker-duplicacy#2]
Hi, I am currently using "saspus/duplicacy-web", and the container is using UTC instead of my local timezone.
I picked between "erichough/duplicacy" and "saspus/duplicacy-web" purely by usage count.

Looking at the config, I suspect I will have the same issue with your container.

Can you please honor the TZ environment variable, and set it in the container, such that the web UI and scheduling uses my local timezone, not UTC?

E.g. log from Unraid creating the container:
```
root@localhost:# /usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker create --name='duplicacy-web' --net='host' --log-opt max-size='50m' --log-opt max-file='1' -e TZ="America/Los_Angeles" -e HOST_OS="Unraid" -e 'USR_ID'='99' -e 'GRP_ID'='100' -v '/mnt/user/appdata/duplicacy-web/config/':'/config':'rw' -v '/mnt/user/appdata/duplicacy-web/logs/':'/logs':'rw' -v '/mnt/user/appdata/duplicacy-web/cache/':'/cache':'rw' -v '/mnt/user/':'/backuproot':'ro' 'saspus/duplicacy-web' 

2f0a27f1b00e89b77f9b1927d8904c43df4e3d0a4d9a025deac3c0d945d6a6c6
```

Note the TZ variable that is automatically added by Unraid.

It also looks like the logs are not externalized in your container, maybe consider doing that so that historic data is preserved between container updates, or did I miss it in config?

**Comment by newbie7800** [comment]
I solved this by putting in my docker compose file a volume which copies from my host to the container the following file (which you an modify to suit your timezone) - /usr/share/zoneinfo/Europe/Berlin:/etc/localtime

Works for me.

**Comment by ehough** [comment]
Like @newbie7800, I generally prefer to bind-mount `/etc/localtime` into the container. But I also don't see why the image shouldn't support setting the timezone via an environment variable.

I've added `tzdata` to the `Dockerfile`, which is needed for the container to respect `TZ`. So the new behavior will be:

1. If `TZ` environment variable is set, the container will use it to set the timezone.
1. If `TZ` is not set, the container will use `/etc/localtime` for the timezone. You can optionally bind-mount your own `/etc/localtime` to set the timezone.

I think this will satisfy everyone, and adding `tzdata` only adds 1 or 2 MB to the image size.
