### ISSUE TITLE
Command line

### ISSUE THREAD

**Issue by newbie7800** [ehough/docker-duplicacy#4]
Hi Eric

Thanks for the docker container and for keeping it updated.  Appreciated.  Is there a way I can access the container command line (for other containers I would use the exec it command with /bin/bash and can access the command line of the container).  Thanks again.

**Comment by ehough** [comment]
Sure thing. Here's how:

1. Inspect the output of `docker ps` to grab the container ID
1. Run `docker exec -it <container-id> sh`

e.g. `docker exec -it 620270361b73 sh`

Bash isn't installed in the image, so you're stuck with good 'ol `sh` :wink:

**Comment by newbie7800** [comment]
Thanks Eric.  Appreciate the help.  Would you mind adding this to the readme.  I think it would help other users.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ehough** [comment]
> Would you mind adding this to the readme.  I think it would help other users.

Good idea! Thanks
